kind: Template
apiVersion: v1
template: data-loader
metadata:
  name: data-loader
objects:

- kind: Job
  apiVersion: batch/v1
  metadata:
    name: ${JOB_NAME}
  spec:
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: ${JOB_NAME}
      spec:
        containers:
          - name: data-loader
            image: quay.io/radanalyticsio/bad-apples-loader
            env:
              - name: SERVER
                value: postgresql
              - name: DBNAME
                value: finance
              - name: USER
                value: username
              - name: PASSWORD
                value: password
        restartPolicy: OnFailure

parameters:
  - name: JOB_NAME
    from: "jdsl-[a-z0-9]{4}"
    generate: expression
    description: unique name for this job run
